# Generated by Django 5.2.16 on 2026-07-21 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='object_type',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='destination',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='template_key',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel', 'status', 'created_at'], name='notif_channel_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['object_type', 'object_id'], name='notif_object_idx'),
        ),
    ]
