# Generated by Django 5.2.16 on 2026-07-15 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def preserve_existing_volunteer_approvals(apps, schema_editor):
    """
    Preserve the status of volunteers who were already operational before
    the formal approval workflow was introduced.

    Existing profiles that were active or had completed the safety
    acknowledgement are treated as previously approved. Their reviewer is
    intentionally left blank because the historical reviewer cannot be
    determined reliably.
    """
    VolunteerProfile = apps.get_model(
        "operations",
        "VolunteerProfile",
    )

    VolunteerProfile.objects.filter(
        models.Q(active=True)
        | models.Q(safety_acknowledged=True)
    ).update(
        approval_status="approved",
        reviewed_at=timezone.now(),
        review_note=(
            "Automatically marked approved during migration because this "
            "volunteer profile was already active or safety-acknowledged "
            "before the formal approval workflow was introduced."
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL,
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volunteerprofile",
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="review_note",
            field=models.TextField(
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteer_profiles_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            preserve_existing_volunteer_approvals,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="active",
            field=models.BooleanField(
                default=False,
            ),
        ),
    ]