# Generated by Django 5.2.16 on 2026-07-20 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_add_volunteer_approval_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupassignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickupassignment',
            name='decline_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickupassignment',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickupassignment',
            name='status',
            field=models.CharField(choices=[('proposed', 'Awaiting volunteer response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='proposed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pickupassignment',
            index=models.Index(fields=['volunteer', 'status', 'scheduled_for'], name='operations__volunte_d980d2_idx'),
        ),
    ]
