# Generated by Django 5.2.16 on 2026-07-13 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('route_date', models.DateField()),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('algorithm', models.CharField(default='nearest_neighbour_v1', max_length=80)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-route_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('distance_from_previous_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='operations.collectionrequest')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='logistics.routeplan')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('route', 'sequence'), name='unique_route_sequence'), models.UniqueConstraint(fields=('route', 'request'), name='unique_route_request')],
            },
        ),
    ]
