import { KeyRound, Save, UserRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { api, errorMessage } from '../api/client'
import { useAuth } from '../context/AuthContext'

export function AccountPage(){
  const {user,refreshUser}=useAuth()
  const [profile,setProfile]=useState({full_name:user?.full_name??'',phone_number:user?.phone_number??''})
  const [passwords,setPasswords]=useState({current_password:'',new_password:'',confirm:''})
  const [profileMessage,setProfileMessage]=useState('')
  const [passwordMessage,setPasswordMessage]=useState('')
  const saveProfile=async(e:FormEvent)=>{e.preventDefault();setProfileMessage('');try{await api.patch('/auth/me/',profile);await refreshUser();setProfileMessage('Profile updated.')}catch(err){setProfileMessage(errorMessage(err))}}
  const changePassword=async(e:FormEvent)=>{e.preventDefault();setPasswordMessage('');if(passwords.new_password!==passwords.confirm){setPasswordMessage('New passwords do not match.');return}try{await api.post('/auth/change-password/',{current_password:passwords.current_password,new_password:passwords.new_password});setPasswords({current_password:'',new_password:'',confirm:''});await refreshUser();setPasswordMessage('Password changed successfully.')}catch(err){setPasswordMessage(errorMessage(err))}}
  return <div className="workspace narrow"><div className="page-head"><div><span className="eyebrow">Identity and security</span><h1>Your account</h1><p>Maintain current contact information and secure your EcoRevive access.</p></div></div><div className="account-grid"><form className="panel account-panel" onSubmit={saveProfile}><div className="panel-head"><div><h2><UserRound size={19}/> Profile</h2><p>Your email and role are controlled separately.</p></div></div><div className="form-stack"><label>Email<input disabled value={user?.email??''}/></label><label>Role<input disabled value={user?.role.replaceAll('_',' ')??''}/></label><label>Full name<input required value={profile.full_name} onChange={e=>setProfile({...profile,full_name:e.target.value})}/></label><label>Phone / WhatsApp<input value={profile.phone_number} onChange={e=>setProfile({...profile,phone_number:e.target.value})}/></label>{profileMessage&&<div className={profileMessage.includes('updated')?'alert alert-info':'alert alert-error'}>{profileMessage}</div>}<button className="button"><Save size={18}/>Save profile</button></div></form><form className="panel account-panel" onSubmit={changePassword}><div className="panel-head"><div><h2><KeyRound size={19}/> Change password</h2><p>Use a unique password of at least 10 characters.</p></div></div><div className="form-stack"><label>Current password<input type="password" required value={passwords.current_password} onChange={e=>setPasswords({...passwords,current_password:e.target.value})}/></label><label>New password<input type="password" minLength={10} required value={passwords.new_password} onChange={e=>setPasswords({...passwords,new_password:e.target.value})}/></label><label>Confirm new password<input type="password" minLength={10} required value={passwords.confirm} onChange={e=>setPasswords({...passwords,confirm:e.target.value})}/></label>{passwordMessage&&<div className={passwordMessage.includes('successfully')?'alert alert-info':'alert alert-error'}>{passwordMessage}</div>}<button className="button"><KeyRound size={18}/>Change password</button></div></form></div></div>
}
