import { Building2, Plus, UserPlus, Users } from 'lucide-react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { api, errorMessage } from '../api/client'
import { Loading } from '../components/Loading'
import { useAuth } from '../context/AuthContext'
import type { AdminUser, Organization, Paginated, UserRole, VolunteerProfile } from '../types'

const roleLabels:Record<UserRole,string>={founder_guardian:'Founder Guardian',founder_recovery:'Founder Recovery',principal_admin:'Principal Administrator',operations_admin:'Operations Administrator',volunteer:'Volunteer',corporate_coordinator:'Corporate Coordinator',resident:'Resident'}

export function AdministrationPage(){
 const {user}=useAuth(); const qc=useQueryClient(); const [section,setSection]=useState<'people'|'volunteers'|'organizations'>('people')
 const users=useQuery({queryKey:['admin-users'],queryFn:async()=>(await api.get<Paginated<AdminUser>>('/users/?page_size=100')).data})
 const volunteers=useQuery({queryKey:['volunteers'],queryFn:async()=>(await api.get<Paginated<VolunteerProfile>>('/volunteer-profiles/?page_size=100')).data})
 const organizations=useQuery({queryKey:['organizations'],queryFn:async()=>(await api.get<Paginated<Organization>>('/organizations/?page_size=100')).data})
 const [newUser,setNewUser]=useState({email:'',full_name:'',phone_number:'',role:'resident' as UserRole,password:''}); const [userError,setUserError]=useState('')
 const createUser=useMutation({mutationFn:()=>api.post('/users/',newUser),onSuccess:()=>{setNewUser({email:'',full_name:'',phone_number:'',role:'resident',password:''});setUserError('');void qc.invalidateQueries({queryKey:['admin-users']})},onError:e=>setUserError(errorMessage(e))})
 const [newVolunteer,setNewVolunteer]=useState({user:'',service_areas:'Dubai',has_vehicle:false,vehicle_description:'',capacity_kg:'0',availability_notes:'',active:true,safety_acknowledged:false});const [volError,setVolError]=useState('')
 const createVolunteer=useMutation({mutationFn:()=>api.post('/volunteer-profiles/',newVolunteer),onSuccess:()=>{setVolError('');void qc.invalidateQueries({queryKey:['volunteers']})},onError:e=>setVolError(errorMessage(e))})
 const [newOrg,setNewOrg]=useState({name:'',organization_type:'corporate',contact_email:'',contact_phone:'',address:''});const [orgError,setOrgError]=useState('')
 const approveOrg=useMutation({mutationFn:(id:string)=>api.post(`/organizations/${id}/approve/`),onSuccess:()=>{void qc.invalidateQueries({queryKey:['organizations']})}})
 const createOrg=useMutation({mutationFn:()=>api.post('/organizations/',newOrg),onSuccess:()=>{setNewOrg({name:'',organization_type:'corporate',contact_email:'',contact_phone:'',address:''});setOrgError('');void qc.invalidateQueries({queryKey:['organizations']})},onError:e=>setOrgError(errorMessage(e))})
 if(users.isLoading||volunteers.isLoading||organizations.isLoading)return <Loading/>
 const allowedRoles:UserRole[]=user?.role==='operations_admin'?['resident','volunteer','corporate_coordinator']:user?.role==='principal_admin'?['resident','volunteer','corporate_coordinator','operations_admin']:['resident','volunteer','corporate_coordinator','operations_admin','principal_admin']
 return <div className="workspace"><div className="page-head"><div><span className="eyebrow">People and partner setup</span><h1>Administration</h1><p>Create operational identities, volunteer profiles and participating organizations.</p></div></div><div className="tabs"><button className={section==='people'?'active':''} onClick={()=>setSection('people')}><Users size={17}/>People</button><button className={section==='volunteers'?'active':''} onClick={()=>setSection('volunteers')}><UserPlus size={17}/>Volunteers</button><button className={section==='organizations'?'active':''} onClick={()=>setSection('organizations')}><Building2 size={17}/>Organizations</button></div>
 {section==='people'&&<div className="admin-split"><form className="panel admin-form" onSubmit={(e:FormEvent)=>{e.preventDefault();createUser.mutate()}}><div className="panel-head"><h2>Create user</h2></div><div className="form-stack"><label>Full name<input required value={newUser.full_name} onChange={e=>setNewUser({...newUser,full_name:e.target.value})}/></label><label>Email<input type="email" required value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})}/></label><label>Phone / WhatsApp<input value={newUser.phone_number} onChange={e=>setNewUser({...newUser,phone_number:e.target.value})}/></label><label>Role<select value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value as UserRole})}>{allowedRoles.map(r=><option key={r} value={r}>{roleLabels[r]}</option>)}</select></label><label>Temporary password<input type="password" minLength={10} required value={newUser.password} onChange={e=>setNewUser({...newUser,password:e.target.value})}/></label>{userError&&<div className="alert alert-error">{userError}</div>}<button className="button" disabled={createUser.isPending}><Plus size={18}/>{createUser.isPending?'Creating…':'Create user'}</button></div></form><section className="panel"><div className="panel-head"><div><h2>Operational users</h2><p>Reserved founder identities appear only in Governance.</p></div></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{(users.data?.results??[]).map(u=><tr key={u.id}><td><strong>{u.full_name}</strong></td><td>{u.email}</td><td>{roleLabels[u.role]}</td><td>{u.is_active?'Active':'Disabled'}</td></tr>)}</tbody></table></div></section></div>}
 {section==='volunteers'&&<div className="admin-split"><form className="panel admin-form" onSubmit={(e:FormEvent)=>{e.preventDefault();createVolunteer.mutate()}}><div className="panel-head"><h2>Create volunteer profile</h2></div><div className="form-stack"><label>Volunteer user<select required value={newVolunteer.user} onChange={e=>setNewVolunteer({...newVolunteer,user:e.target.value})}><option value="">Select user</option>{(users.data?.results??[]).filter(u=>u.role==='volunteer'&&!(volunteers.data?.results??[]).some(v=>v.user===u.id)).map(u=><option key={u.id} value={u.id}>{u.full_name} — {u.email}</option>)}</select></label><label>Service areas<input value={newVolunteer.service_areas} onChange={e=>setNewVolunteer({...newVolunteer,service_areas:e.target.value})}/></label><label className="check"><input type="checkbox" checked={newVolunteer.has_vehicle} onChange={e=>setNewVolunteer({...newVolunteer,has_vehicle:e.target.checked})}/><span>Has access to a vehicle</span></label><label>Vehicle description<input value={newVolunteer.vehicle_description} onChange={e=>setNewVolunteer({...newVolunteer,vehicle_description:e.target.value})}/></label><label>Capacity (kg)<input type="number" min="0" step="1" value={newVolunteer.capacity_kg} onChange={e=>setNewVolunteer({...newVolunteer,capacity_kg:e.target.value})}/></label><label className="check"><input type="checkbox" checked={newVolunteer.safety_acknowledged} onChange={e=>setNewVolunteer({...newVolunteer,safety_acknowledged:e.target.checked})}/><span>Safety process acknowledged</span></label>{volError&&<div className="alert alert-error">{volError}</div>}<button className="button" disabled={createVolunteer.isPending}><Plus size={18}/>Create profile</button></div></form><section className="panel"><div className="panel-head"><h2>Volunteer roster</h2></div><div className="card-list">{(volunteers.data?.results??[]).map(v=><article key={v.id}><div className="avatar">{v.user_name[0]}</div><div><strong>{v.user_name}</strong><small>{v.user_email}</small><p>{v.service_areas||'Dubai'} · {v.has_vehicle?v.vehicle_description||'Vehicle available':'No vehicle'}</p></div><span>{v.capacity_kg} kg</span></article>)}</div></section></div>}
 {section==='organizations'&&<div className="admin-split"><form className="panel admin-form" onSubmit={(e:FormEvent)=>{e.preventDefault();createOrg.mutate()}}><div className="panel-head"><h2>Add organization</h2></div><div className="form-stack"><label>Name<input required value={newOrg.name} onChange={e=>setNewOrg({...newOrg,name:e.target.value})}/></label><label>Type<select value={newOrg.organization_type} onChange={e=>setNewOrg({...newOrg,organization_type:e.target.value})}><option value="corporate">Corporate office</option><option value="school">School</option><option value="community">Residential community</option><option value="nonprofit">Community organization</option></select></label><label>Contact email<input type="email" required value={newOrg.contact_email} onChange={e=>setNewOrg({...newOrg,contact_email:e.target.value})}/></label><label>Contact phone<input value={newOrg.contact_phone} onChange={e=>setNewOrg({...newOrg,contact_phone:e.target.value})}/></label><label>Address<textarea value={newOrg.address} onChange={e=>setNewOrg({...newOrg,address:e.target.value})}/></label>{orgError&&<div className="alert alert-error">{orgError}</div>}<button className="button" disabled={createOrg.isPending}><Plus size={18}/>Add organization</button></div></form><section className="panel"><div className="panel-head"><h2>Organizations</h2></div><div className="card-list">{(organizations.data?.results??[]).map(o=><article key={o.id}><div className="org-icon"><Building2/></div><div><strong>{o.name}</strong><small>{o.contact_email}</small><p>{o.organization_type.replaceAll('_',' ')} · {o.address||'Dubai'}</p></div>{o.approved?<span>Approved</span>:<button type="button" className="button button-small button-ghost" onClick={()=>approveOrg.mutate(o.id)}>Approve</button>}</article>)}</div></section></div>}</div>
}
