import { KeyRound, LockKeyhole, Plus, ShieldCheck, UserCog } from 'lucide-react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { api, errorMessage } from '../api/client'
import { Loading } from '../components/Loading'
import { useAuth } from '../context/AuthContext'
import type { AdminUser, AuditEvent, GovernanceIdentity, Paginated } from '../types'

export function GovernancePage(){
 const {user}=useAuth();const qc=useQueryClient();const identities=useQuery({queryKey:['governance-identities'],queryFn:async()=>(await api.get<Paginated<GovernanceIdentity>>('/governance/identities/')).data});const audit=useQuery({queryKey:['audit'],queryFn:async()=>(await api.get<Paginated<AuditEvent>>('/governance/audit-events/?page_size=20')).data});const users=useQuery({queryKey:['admin-users'],queryFn:async()=>(await api.get<Paginated<AdminUser>>('/users/?page_size=100')).data});const canControl=['founder_guardian','founder_recovery'].includes(user?.role??'')
 const admins=(users.data?.results??[]).filter(u=>['principal_admin','operations_admin'].includes(u.role));const toggle=useMutation({mutationFn:({id,is_active}:{id:string;is_active:boolean})=>api.patch(`/users/${id}/`,{is_active}),onSuccess:()=>{void qc.invalidateQueries({queryKey:['admin-users']});void qc.invalidateQueries({queryKey:['audit']})}})
 const [principal,setPrincipal]=useState({full_name:'',email:'',phone_number:'',role:'principal_admin',password:''});const [principalError,setPrincipalError]=useState('');const appoint=useMutation({mutationFn:()=>api.post('/users/',principal),onSuccess:()=>{setPrincipal({full_name:'',email:'',phone_number:'',role:'principal_admin',password:''});setPrincipalError('');void qc.invalidateQueries({queryKey:['admin-users']})},onError:e=>setPrincipalError(errorMessage(e))})
 if(identities.isLoading||audit.isLoading||users.isLoading)return <Loading/>
 return <div className="workspace"><div className="page-head"><div><span className="eyebrow">Executive security register</span><h1>Governance identities</h1><p>Disclosed founder and emergency authorities are separated from routine operational user management.</p></div></div><div className="governance-grid">{(identities.data?.results??[]).map(identity=><article className="governance-card" key={identity.id}><div className="governance-icon">{identity.role==='founder_recovery'?<KeyRound/>:<ShieldCheck/>}</div><div><span>{identity.role_label}</span><h2>{identity.full_name}</h2><p>{identity.email}</p></div><span className={identity.is_active?'status status-completed':'status status-cancelled'}>{identity.is_active?'Active':'Disabled'}</span><footer><LockKeyhole size={15}/>Protected from normal application modification</footer></article>)}</div>
 <div className="governance-controls"><section className="panel"><div className="panel-head"><div><h2><UserCog size={19}/>Administrative authority</h2><p>Founder governance may suspend or restore operational administrators.</p></div></div><div className="card-list">{admins.map(admin=><article key={admin.id}><div className="avatar">{admin.full_name[0]}</div><div><strong>{admin.full_name}</strong><small>{admin.email}</small><p>{admin.role.replaceAll('_',' ')}</p></div>{canControl?<button className={`button button-small ${admin.is_active?'button-ghost':''}`} onClick={()=>toggle.mutate({id:admin.id,is_active:!admin.is_active})}>{admin.is_active?'Suspend':'Restore'}</button>:<span>{admin.is_active?'Active':'Suspended'}</span>}</article>)}{admins.length===0&&<div className="empty compact"><p>No delegated administrators yet.</p></div>}</div></section>{canControl&&<form className="panel admin-form" onSubmit={(e:FormEvent)=>{e.preventDefault();appoint.mutate()}}><div className="panel-head"><div><h2>Appoint Principal Administrator</h2><p>This is a reserved founder-governance action.</p></div></div><div className="form-stack"><label>Full name<input required value={principal.full_name} onChange={e=>setPrincipal({...principal,full_name:e.target.value})}/></label><label>Email<input type="email" required value={principal.email} onChange={e=>setPrincipal({...principal,email:e.target.value})}/></label><label>Phone<input value={principal.phone_number} onChange={e=>setPrincipal({...principal,phone_number:e.target.value})}/></label><label>Temporary password<input type="password" minLength={10} required value={principal.password} onChange={e=>setPrincipal({...principal,password:e.target.value})}/></label>{principalError&&<div className="alert alert-error">{principalError}</div>}<button className="button" disabled={appoint.isPending}><Plus size={18}/>Appoint administrator</button></div></form>}</div>
 <section className="panel"><div className="panel-head"><div><h2>Governance audit trail</h2><p>Administrative and emergency actions are retained as append-only application events.</p></div></div><div className="audit-list">{(audit.data?.results??[]).map(event=><div key={event.id}><span className="audit-dot"/><div><strong>{event.summary}</strong><small>{event.actor_email??'System'} · {new Date(event.created_at).toLocaleString()}</small></div><code>{event.event_type}</code></div>)}{(audit.data?.results??[]).length===0&&<div className="empty compact"><h3>No governance events recorded</h3><p>Bootstrap and protected-account events will appear here.</p></div>}</div></section><div className="alert alert-info"><strong>Important:</strong> this is not a covert account mechanism. Recovery authority is formally disclosed, narrowly scoped and should be paired with hardware-key authentication, infrastructure separation and executive governance documentation.</div></div>
}
